# Generated by Django 5.2.16 on 2026-07-22 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_issue_public_id_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="ip_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="issue",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="IssueUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField(verbose_name="update")),
                ("author_name", models.CharField(blank=True, max_length=100, verbose_name="name")),
                (
                    "photo",
                    models.ImageField(blank=True, upload_to="updates/%Y/%m/", verbose_name="photo"),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("ip_hash", models.CharField(blank=True, editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="core.issue",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ip_hash", models.CharField(editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="core.issue",
                    ),
                ),
                (
                    "update",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="core.issueupdate",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("issue__isnull", False)),
                        fields=("issue", "ip_hash"),
                        name="unique_issue_flag_per_ip",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("update__isnull", False)),
                        fields=("update", "ip_hash"),
                        name="unique_update_flag_per_ip",
                    ),
                ],
            },
        ),
    ]
