# Generated by Django 5.2.16 on 2026-07-22 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_issue_claim_token_hash_issue_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                condition=models.Q(("is_hidden", False)),
                fields=["-created_at"],
                name="issue_public_recent",
            ),
        ),
        migrations.AddConstraint(
            model_name="flag",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("issue__isnull", False), ("update__isnull", True)),
                    models.Q(("issue__isnull", True), ("update__isnull", False)),
                    _connector="OR",
                ),
                name="flag_exactly_one_target",
            ),
        ),
    ]
