# Generated by Django 5.2.16 on 2026-07-22 07:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_issue_issue_public_recent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("state", "State"),
                            ("district", "District"),
                            ("council", "Local council area"),
                            ("other", "Other"),
                        ],
                        default="council",
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="boundary"
                    ),
                ),
                (
                    "external_code",
                    models.CharField(blank=True, max_length=30, verbose_name="external code"),
                ),
                ("generation", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CategoryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.SlugField(unique=True, verbose_name="name")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="address"),
        ),
        migrations.AddField(
            model_name="issue",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="issue",
            name="closure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_responsible", "No responsible agency"),
                    ("duplicate", "Duplicate"),
                    ("referred", "Referred elsewhere"),
                    ("invalid", "Not a valid issue"),
                    ("wont_fix", "Won't be fixed"),
                ],
                max_length=20,
                verbose_name="closure reason",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="core.issue",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="extra_answers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="issue",
            name="fixed_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reporter", "Reporter"),
                    ("community", "Community"),
                    ("staff", "Staff"),
                    ("agency", "Agency"),
                ],
                max_length=10,
                verbose_name="fixed by",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="language",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="issue",
            name="non_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="issue",
            name="send_questionnaire",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="source_channel",
            field=models.CharField(
                choices=[
                    ("web", "Web form"),
                    ("url_import", "URL import"),
                    ("browser_import", "Browser import"),
                    ("api", "API"),
                    ("staff", "Staff-filed"),
                ],
                default="web",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="issueupdate",
            name="new_status",
            field=models.CharField(
                blank=True,
                choices=[("open", "Open"), ("fixed", "Fixed"), ("closed", "Closed")],
                max_length=10,
                verbose_name="new status",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="areas",
            field=models.ManyToManyField(blank=True, related_name="issues", to="core.area"),
        ),
        migrations.CreateModel(
            name="Body",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True, verbose_name="name")),
                ("slug", models.SlugField(unique=True)),
                (
                    "dispatch_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="dispatch email"),
                ),
                ("homepage", models.URLField(blank=True, verbose_name="homepage")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "areas",
                    models.ManyToManyField(blank=True, related_name="bodies", to="core.area"),
                ),
            ],
            options={
                "verbose_name_plural": "bodies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("unconfirmed", "Unconfirmed"),
                            ("inactive", "Inactive"),
                        ],
                        default="unconfirmed",
                        max_length=12,
                    ),
                ),
                (
                    "dispatch_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="dispatch email override"
                    ),
                ),
                ("photo_required", models.BooleanField(default=False)),
                ("non_public", models.BooleanField(default=False)),
                ("prefer_if_multiple", models.BooleanField(default=False)),
                ("sispaa_category", models.CharField(blank=True, max_length=100)),
                ("extra_fields", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="core.body",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="core.categorygroup",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="core.category",
            ),
        ),
        migrations.CreateModel(
            name="Filing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "target_name",
                    models.CharField(blank=True, max_length=150, verbose_name="filed with"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sispaa", "SISPAA"),
                            ("manual", "Manual / recorded"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recorded", "Recorded"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("acknowledged", "Acknowledged"),
                            ("in_progress", "In progress"),
                            ("closed", "Closed by agency"),
                        ],
                        default="recorded",
                        max_length=15,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="their reference number"
                    ),
                ),
                (
                    "external_status",
                    models.CharField(blank=True, max_length=100, verbose_name="their status"),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("filed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, verbose_name="note")),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filings",
                        to="core.body",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filings",
                        to="core.issue",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by_links",
                        to="core.issue",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocking_links",
                        to="core.issue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("issue", "One issue"), ("area", "Reports near a point")],
                        default="issue",
                        max_length=10,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("confirmed", models.BooleanField(default=False)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="core.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="issue",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="issues", to="core.tag"),
        ),
        migrations.AddConstraint(
            model_name="issue",
            constraint=models.CheckConstraint(
                condition=models.Q(("duplicate_of", models.F("id")), _negated=True),
                name="issue_not_duplicate_of_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("body", "name"), name="unique_category_per_body"
            ),
        ),
        migrations.AddConstraint(
            model_name="filing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("body__isnull", False),
                    models.Q(("target_name", ""), _negated=True),
                    _connector="OR",
                ),
                name="filing_has_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuelink",
            constraint=models.UniqueConstraint(
                fields=("blocker", "blocked"), name="unique_issue_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="issuelink",
            constraint=models.CheckConstraint(
                condition=models.Q(("blocker", models.F("blocked")), _negated=True),
                name="issue_link_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "issue"), _negated=True),
                    ("issue__isnull", False),
                    _connector="OR",
                ),
                name="issue_subscription_has_issue",
            ),
        ),
    ]
