# Generated by Django 5.2.16 on 2026-07-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_media_split"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="session_key",
        ),
        migrations.AddField(
            model_name="media",
            name="owner_token",
            field=models.CharField(
                blank=True, editable=False, max_length=64, verbose_name="owner token"
            ),
        ),
    ]
